version: "3.9"

services:
  rag-faiss-app:
    image: rag-faiss-streamlit-app-ecr-repo:v2   
    build: .
    container_name: rag-faiss-streamlit-app-new
    ports:
      - "8501:8501"
      - "8000:8000"
    env_file:
      - app.env
    volumes:
      - ./data:/app/data
      - ./db1:/app/db1
    restart: always
